version: "3.9"

services:
  app-install:
    build: php
    working_dir: /app
    command: composer install
    volumes:
      - .:/app
    profiles:
      - donotstart
    env_file:
      .env

  app-build:
    build: php
    working_dir: /app
    command: sh /app/build.sh
    volumes:
      - .:/app
    profiles:
      - donotstart
    env_file:
      .env

  app-run:
    build: php
    working_dir: /app
    command: php /app/src/run.php
    volumes:
      - .:/app
    profiles:
      - donotstart
    env_file:
      .env